# Generated by Django 5.2.10 on 2026-02-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printorder',
            old_name='color_type',
            new_name='color_mode',
        ),
        migrations.RemoveField(
            model_name='printorder',
            name='page_range',
        ),
        migrations.RemoveField(
            model_name='printorder',
            name='status',
        ),
        migrations.AddField(
            model_name='printorder',
            name='binding',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='printorder',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='printorder',
            name='paper_size',
            field=models.CharField(default='A4', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printorder',
            name='print_side',
            field=models.CharField(default='single', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printorder',
            name='copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
