# Generated by Django 5.2.10 on 2026-02-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0004_printorder_notes_alter_printorder_color_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printorder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='printorder',
            name='notes',
        ),
        migrations.AlterField(
            model_name='printorder',
            name='binding',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='color_mode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='document',
            field=models.FileField(upload_to='print_uploads/'),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='paper_size',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='print_side',
            field=models.CharField(max_length=10),
        ),
    ]
