# Generated by Django 5.2.10 on 2026-02-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0005_remove_printorder_created_at_remove_printorder_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printorder',
            name='binding',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='color_mode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='document',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='paper_size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='print_side',
            field=models.CharField(max_length=20),
        ),
    ]
