# Generated by Django 5.2.10 on 2026-02-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0007_printorder_created_at_printorder_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('printing', 'Printing'), ('done', 'Done')], default='pending', max_length=10),
        ),
    ]
