# Generated by Django 5.2.10 on 2026-02-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0002_rename_color_type_printorder_color_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printorder',
            name='file',
        ),
        migrations.RemoveField(
            model_name='printorder',
            name='instructions',
        ),
        migrations.AddField(
            model_name='printorder',
            name='document',
            field=models.FileField(default='dummy.txt', upload_to='prints/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printorder',
            name='binding',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='color_mode',
            field=models.CharField(default='bw', max_length=10),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='paper_size',
            field=models.CharField(default='A4', max_length=10),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='print_side',
            field=models.CharField(default='single', max_length=10),
        ),
    ]
