# Generated by Django 5.2.10 on 2026-02-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0003_remove_printorder_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='color_mode',
            field=models.CharField(choices=[('bw', 'Black & White'), ('color', 'Color')], default='bw', max_length=10),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='document',
            field=models.FileField(upload_to='print_jobs/'),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='paper_size',
            field=models.CharField(choices=[('A4', 'A4'), ('A3', 'A3')], default='A4', max_length=5),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='print_side',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double')], default='single', max_length=10),
        ),
    ]
