# Generated by Django 5.2.10 on 2026-02-10 06:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0006_alter_printorder_binding_alter_printorder_color_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printorder',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='binding',
            field=models.CharField(choices=[('none', 'No Binding'), ('spiral', 'Spiral'), ('thermal', 'Thermal'), ('hardcover', 'Hardcover')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='color_mode',
            field=models.CharField(choices=[('bw', 'Black & White'), ('color', 'Color')], max_length=10),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='paper_size',
            field=models.CharField(choices=[('A4', 'A4'), ('A3', 'A3')], max_length=5),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='print_side',
            field=models.CharField(choices=[('single', 'Single Sided'), ('double', 'Double Sided')], max_length=10),
        ),
    ]
