# Generated by Django 5.2.10 on 2026-03-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0009_printorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
